Repository dandi/zarr_checksum, pull requests merged in 2023-11, with the labels that each got.

#20 Fix license declaration
  pyproject.toml
Labels: skip-release

#18 Test against Python 3.12
  .github/workflows/test.yml
Labels: skip-release

#15 Add codespell config, workflow, and fix some typos
  .github/workflows/codespell.yml
  README.md
  pyproject.toml
  zarr_checksum/checksum.py
Labels: skip-release

#17 Avoid importing zarr library unless necessary
  pyproject.toml
  zarr_checksum/generators.py
Labels: internal

#19 Use Dependabot to auto-update GitHub Actions and Python dependency versions
  .github/dependabot.yml
Labels: skip-release

#22 Add `.pre-commit-config.yaml`
  .pre-commit-config.yaml
Labels: skip-release

#23 Update for Pydantic v2
  poetry.lock
  pyproject.toml
  zarr_checksum/checksum.py
Labels: dependencies
